routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
// Start Add +

    //Stores
    Route::resource('/store', App\Http\Controllers\Admin\StoresController::class);

    //Departments
    Route::resource('/departments', App\Http\Controllers\Admin\DepartmentsController::class);

    //Page Names
    Route::resource('/pages', App\Http\Controllers\Admin\PagesController::class);

    //Employees
    Route::resource('/employees', App\Http\Controllers\Admin\EmployeesController::class);

    //Campaigns
    Route::resource('/campaigns', App\Http\Controllers\Admin\CampaignController::class);

    //Creative Types
    Route::resource('/creative-types', App\Http\Controllers\Admin\CreativeTypeController::class);

    // Strategies
    Route::resource('/strategies', App\Http\Controllers\Admin\StrategyController::class);

    // Status
    Route::resource('/status', App\Http\Controllers\Admin\StatusController::class);

    // Ads Type
    Route::resource('/ads-type', App\Http\Controllers\Admin\AdsTypeController::class);

    // Ads Strategy
    Route::resource('/ads-strategy', App\Http\Controllers\Admin\AdsStrategyController::class);

    // Agent Teams
    Route::resource('/agent-teams', App\Http\Controllers\Admin\AgentTeamsController::class);

// End Add +


// Centralized
Route::resource('/centralized', App\Http\Controllers\All\CentralizeController::class);
Route::get('/running', [App\Http\Controllers\All\CentralizeController::class, 'running'])->name('centralized.running');
Route::get('/killed', [App\Http\Controllers\All\CentralizeController::class, 'killed'])->name('centralized.killed');

// Trackers
Route::get('/budget-per-product', [App\Http\Controllers\TrackersController::class, 'budgetPerProducts'])->name('budget-per-product.budgetPerProducts');
Route::get('/budget-per-product/{product_name}', [App\Http\Controllers\TrackersController::class, 'showBudgetPerProducts'])->name('budget-per-product.showBudgetPerProducts');

app/Http/Controllers/Admin/AdsStrategyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\AdStrategy;

use Session;

class AdsStrategyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adstrategies = AdStrategy::all();
        return view('admin.ads-strategy.index', compact('adstrategies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'ads_strategy' => 'required|unique:ad_strategies',
        ]);

        $adstrategies = new AdStrategy;
        $adstrategies->ads_strategy = $request->ads_strategy;
        $adstrategies->save();

        Session::flash('success', 'Ads Strategy was created successfully!');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/ads-strategy/index.blade.php
@extends('main')

@section('content')

@if(session('success'))
<div class="alert alert-success alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<h5><i class="icon fas fa-check"></i> Success!</h5>
{{session('success')}}
</div>
@elseif($errors->any())
<div class="alert alert-danger alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h5><i class="icon fas fa-times"></i>Error!</h5>
@foreach($errors->all() as $error)
  <p>{{$error}}</p>
@endforeach
</div>
@endif

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Ads Strategy</h1>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#add-ads-strategy">Add<i class="fas fa-plus"></i></button>
                        <!-- Add Departments Modal -->
                        <div class="modal fade" id="add-ads-strategy">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h4 class="modal-title">Add Ads Strategy</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                    <form method="POST" action="{{ route('ads-strategy.store') }}">
                                        @csrf
                                        <div class="form-group">
                                            <label>Ads Type</label>
                                            <input style="text-transform: capitalize;" type="text" class="form-control" name="ads_strategy" placeholder="Ads Strategy">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Add</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Modal -->
                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Ads Strategy</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($adstrategies as $adstrategy)
                                <tr>
                                    <td style="text-transform: capitalize;">{{$adstrategy->ads_strategy}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button>
                                            <button type="button" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection