routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
// Start Add +

    //Stores
    Route::resource('/store', App\Http\Controllers\Admin\StoresController::class);

    //Departments
    Route::resource('/departments', App\Http\Controllers\Admin\DepartmentsController::class);

    //Page Names
    Route::resource('/pages', App\Http\Controllers\Admin\PagesController::class);

    //Employees
    Route::resource('/employees', App\Http\Controllers\Admin\EmployeesController::class);

    //Campaigns
    Route::resource('/campaigns', App\Http\Controllers\Admin\CampaignController::class);

    //Creative Types
    Route::resource('/creative-types', App\Http\Controllers\Admin\CreativeTypeController::class);

    // Strategies
    Route::resource('/strategies', App\Http\Controllers\Admin\StrategyController::class);

    // Status
    Route::resource('/status', App\Http\Controllers\Admin\StatusController::class);

    // Ads Type
    Route::resource('/ads-type', App\Http\Controllers\Admin\AdsTypeController::class);

    // Ads Strategy
    Route::resource('/ads-strategy', App\Http\Controllers\Admin\AdsStrategyController::class);

    // Agent Teams
    Route::resource('/agent-teams', App\Http\Controllers\Admin\AgentTeamsController::class);

// End Add +


// Centralized
Route::resource('/centralized', App\Http\Controllers\All\CentralizeController::class);
Route::get('/running', [App\Http\Controllers\All\CentralizeController::class, 'running'])->name('centralized.running');
Route::get('/killed', [App\Http\Controllers\All\CentralizeController::class, 'killed'])->name('centralized.killed');

// Trackers
Route::get('/budget-per-product', [App\Http\Controllers\TrackersController::class, 'budgetPerProducts'])->name('budget-per-product.budgetPerProducts');
Route::get('/budget-per-product/{product_name}', [App\Http\Controllers\TrackersController::class, 'showBudgetPerProducts'])->name('budget-per-product.showBudgetPerProducts');

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    protected $fillable = [
        'store_name',
        'store_code',
    ];

    public function pages()
    {
        return $this->belongsTo('Pages', 'store_id');
    }

    public function teams()
    {
        return $this->belongsTo('App\Models\AgentTeam', 'team_id');
    }
}

app/Http/Controllers/Admin/StoresController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Store;
use App\Models\AgentTeam;

use Session;

class StoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stores = Store::all();
        $teams = AgentTeam::all();
        return view('admin.store.index', compact('stores', 'teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'store_name' => 'required|unique:stores',
            'store_code' => 'required|unique:stores',
        ]);

        $stores = new Store;
        $stores->store_name = $request->store_name;
        $stores->store_code = $request->store_code;
        $stores->team_id = $request->team_id;
        $stores->save();

        Session::flash('success', 'Store was Created Successfully!');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $stores = Store::find($id);
        return view('admin.store.show', compact('stores'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,
        [
            'store_name' => 'required',
            'store_code' => 'required',
        ]);

        $stores = Store::find($id);
        $stores->store_name = $request->store_name;
        $stores->store_code = $request->store_code;
        $stores->team_id = $request->team_id;
        $stores->save();

        Session::flash('success', 'Store was Updated Successfully!');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $stores = Store::find($id);
        $stores->delete();
        
        Session::flash('success', 'Store was deleted successfully!');
        return redirect()->back();
    }
}

resources/views/admin/store/index.blade.php
@extends('main')

@section('stylesheets')

<link rel="stylesheet" href="{{ asset('../css/backend/bootstrap-4.min.css') }}">

@endsection

@section('content')

@if(session('success'))
<div class="alert alert-success alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<h5><i class="icon fas fa-check"></i> Success!</h5>
{{session('success')}}
</div>
@elseif($errors->any())
<div class="alert alert-danger alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h5><i class="icon fas fa-times"></i>Error!</h5>
@foreach($errors->all() as $error)
  <p>{{$error}}</p>
@endforeach
</div>
@endif

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Stores</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#add-stores">Add <i class=" fas fa-plus"></i></button>
                <!-- User Create Modal -->
                <div class="modal fade" id="add-stores">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h4 class="modal-title">Add Store</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            <form method="POST" action="{{ route('store.store') }}">
                            @csrf
                                <div class="form-group">
                                    <label>Store Name</label>
                                    <input type="text" style="text-transform: capitalize;" class="form-control" name="store_name" placeholder="Store Name">
                                </div>
                                <div class="form-group">
                                    <label>Store Code</label>
                                    <input type="text" style="text-transform: uppercase;"class="form-control" name="store_code" placeholder="Store Code">
                                </div>
                                <div class="form-group">
                                    <label>Team Assign</label>
                                    <select style="text-transform: capitalize;" class="form-control select2" style="width: 100%;" name="team_id">
                                        <option value=""selected>-- Select Team --</option>
                                        @foreach($teams as $team)
                                        <option value="{{$team->id}}">{{$team->agent_team}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </form>
                            </div>
                        </div>
                    <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Store Name</th>
                      <th>Store Code</th>
                      <th>Team</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($stores as $store)
                    <tr>
                      <td style="text-transform: capitalize;">{{ $store->store_name }}</td>
                      <td style="text-transform: uppercase;">{{ $store->store_code }}</td>
                      <td style="text-transform: capitalize;">@if(!empty($store->team_id)){{ $store->teams->agent_team}} @endif</td>
                      <td>
                        <div class="btn-group">
                            <!-- <a href="{{ route('store.show',$store->id) }}"><button type="button" class="btn btn-success"><i class="fas fa-eye"></i></button></a> -->
                            <a href="#"><button type="button" class="btn btn-success"><i class="fas fa-eye"></i></button></a>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#edit-stores-{{$store->id}}"><i class="fas fa-edit"></i></button>
                            <!-- User Create Modal -->
                            <div class="modal fade" id="edit-stores-{{$store->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h4 class="modal-title">Edit Store</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body">
                                        <form method="POST" action="{{ route('store.update', $store->id) }}">
                                        @method('PUT')
                                        @csrf
                                            <div class="form-group">
                                                <label>Store Name</label>
                                                <input type="text" class="form-control" name="store_name" value="{{ $store->store_name }}">
                                            </div>
                                            <div class="form-group">
                                                <label>Store Code</label>
                                                <input type="text" class="form-control" name="store_code" value="{{ $store->store_code }}">
                                            </div>
                                            <div class="form-group">
                                            <label>Team Assign</label>
                                              <select style="text-transform: capitalize;" class="form-control select2" style="width: 100%;" name="team_id">
                                                <option value="@if(!empty($store->team_id)) {{$store->team_id}} @endif" selected>-- Select Team --</option>
                                                @foreach($teams as $team)
                                                <option value="{{$team->id}}">{{$team->agent_team}}</option>
                                                @endforeach
                                              </select>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-success">Update</button>
                                            </div>
                                        </form>
                                        </div>
                                    </div>
                                <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-store-{{$store->id}}"><i class="fas fa-trash"></i></button>
                            <!-- Delete Store Modal -->
                            <div class="modal fade" id="delete-store-{{$store->id}}">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                  <h4 class="modal-title">Are you sure to delete this store?</h4>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                  </div>
                                  <div class="modal-body" style="text-align: right;">
                                  <form method="POST" action="{{ route('store.destroy',$store->id) }}">
                                  @csrf
                                  @method('DELETE')
                                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                  <button type="submit" class="btn btn-danger">Delete</button>
                                  </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- End Modal -->
                        </div>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
    </div>
</section>
@endsection

resources/views/admin/store/show.blade.php
@extends('main')

@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{$stores->store_name}}</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#add-pagenames">Add <i class=" fas fa-plus"></i></button>
                <!-- User Create Modal -->
                <div class="modal fade" id="add-pagenames">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h4 class="modal-title">Add Page Name</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            <form method="POST" action="#">
                            @csrf
                                <div class="form-group">
                                    <label>Store Name</label>
                                    <input type="text" class="form-control" name="page_name" placeholder="Page Name">
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </form>
                            </div>
                        </div>
                    <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Store Name</th>
                      <th>Store Code</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Example</td>
                      <td>Example</td>
                      <td>
                        <div class="btn-group">
                            <a href="#"><button type="button" class="btn btn-success"><i class="fas fa-eye"></i></button></a>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#"><i class="fas fa-edit"></i></button>
                            <!-- User Create Modal -->
                            <div class="modal fade" id="#">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h4 class="modal-title">Edit Page Name</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body">
                                        <form method="#" action="#">
                                            <div class="form-group">
                                                <label>Store Name</label>
                                                <input type="text" class="form-control" name="" value="">
                                            </div>
                                            <div class="form-group">
                                                <label>Store Code</label>
                                                <input type="text" class="form-control" name="" value="">
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-success">Update</button>
                                            </div>
                                        </form>
                                        </div>
                                    </div>
                                <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                            <button type="button" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
    </div>
</section>

@endsection